#!/usr/bin/env bash

fail() { 
  echo "$*" >&2
  exit 1
}

user() {
  local _action=$1 ; shift
  case ${_action} in
    (exec)  exec chpst -u "${userName}:${groupName}" "$@" ;;
    (run)   chpst -u "${userName}:${groupName}" "$@"      ;;
    (chown) chown -R "${userName}:${groupName}" "$@"      ;;
  esac
}

send_signal() { 
  if [[ -s ${pidFile} ]]
  then
    pid=$(head -1 ${pidFile})
    if (( ${pid:-0} > 0 ))
    then kill -${1} ${pid}
    fi
  fi
}

turn_debugging_on() {
  echo "Turning Debugging On"
  export PS4='+(${BASH_SOURCE}:${LINENO})> ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
  export DEBUG="true" 
  set -x
  set -v
}

add_packages_to_path() { # Add all packages' /bin & /sbin into $PATH
  for _path in $(ls -d /var/vcap/packages/*/*bin)
  do PATH="${_path}:${PATH}"
  done ; export PATH
}

configure_job_paths() {
  _paths=(
    "${jobPath}"
    "${jobRunPath}"
    "${jobLogPath}"
    "${jobTmpPath}"
    "${jobStorePath}"
  )

  for _path in "${_paths[@]}"
  do
    if ! [[ -d ${_path} ]]
    then
      mkdir -p "${_path}"
      chown -R ${userName}:${groupName} "${_path}"
      chmod 0775 "${_path}"
    fi
  done
}

