---
meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

jobs:
  - name: pgbdr
    instances: 2
    networks:
      - name: pgbdr
    persistent_disk: (( meta.persistent_disk ))
    properties:
      pgbdr:

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: pgbdr
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
