---
meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-centos-7-go_agent
    version: latest

jobs:
  - name: rdpg

    resource_pool: pool_z1
    persistent_disk: (( meta.persistent_disk ))

    networks:
      - name: rdpg
        default: [ dns, gateway ]
        static_ips: [ 10.10.1.10-10.10.1.14 ]

    properties:
      pgbdr:
        #debug: "true"
        hba: ""
        nodes:
          - 10.10.1.10
          - 10.10.1.11
          - 10.10.1.12
          - 10.10.1.13
          - 10.10.1.14
        max_connections: "2000"
        shared_buffers: "512MB"
        effective_cache_size: "1536MB"
        work_mem: "262kB"
        maintenance_work_mem: "128MB"
        checkpoint_segments: "32"
        checkpoint_completion_target: "0.7"
        wal_buffers: "16MB"
        default_statistics_target: "100"
      pgbouncer:
        #debug: "true"
        admin_pass: "rdpgadmin"
      consul: {}
        #debug: "true"
      haproxy:
        admin_user: rdpghaadmin
        admin_pass: Changeme123
        admin_port: 9999

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: pool_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: rdpg
    type: manual
    subnets:
    - range: 10.10.1.0/24
      name: rdpg
      dns: [10.10.0.2]
      gateway: 10.10.1.1
      reserved: 
        - 10.10.1.2-10.10.1.5
        - 10.10.1.250-10.10.1.254
      static: 
        - 10.10.1.10-10.10.1.60
      cloud_properties:
        subnet_ids: (( meta.subnet_ids ))
        security_groups: (( meta.security_groups ))

  - name: floating
    type: vip
    cloud_properties:
      subnet_ids: (( meta.subnet_ids ))
      security_groups: (( meta.security_groups ))

properties: {}

