---
meta:
  environment: (( merge ))
  dns_root: (( merge ))
  security_groups: (( merge ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-centos-7-go_agent
    version: latest

jobs:
  - name: rdpg
    instances: 5
    resource_pool: default
    persistent_disk: (( meta.persistent_disk ))
    templates: (( meta.templates ))
    networks:
      - name: rdpg
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.10.1.10
          - 10.10.1.11
          - 10.10.1.12
          - 10.10.1.13
          - 10.10.1.14
    properties:
      pgbdr:
        #debug: "true"
        hba: ""
        nodes:
          - 10.10.1.10
          - 10.10.1.11
          - 10.10.1.12
          - 10.10.1.13
          - 10.10.1.14
        max_connections: "2000"
        shared_buffers: "512MB"
        effective_cache_size: "1536MB"
        work_mem: "262kB"
        maintenance_work_mem: "128MB"
        checkpoint_segments: "32"
        checkpoint_completion_target: "0.7"
        wal_buffers: "16MB"
        default_statistics_target: "100"
      pgbouncer:
        #debug: "true"
        admin_pass: "rdpgadmin"
      consul: {}
        #debug: "true"

compilation:
  cloud_properties:
    instance_type: m1.small

resource_pools:
  - name: small_z1
    cloud_properties:
      instance_type: m1.small

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: rdpg
    type: dynamic
    cloud_properties:
      security_groups: (( meta.security_groups ))
