---
meta:
  environment: (( merge ))
  persistent_disk: 4096

  stemcell:
    name: bosh-aws-xen-centos-7-go_agent
    version: latest

disk_pools:
- name: rdpgsc_disk
  disk_size: 1_024_000
  cloud_properties: {}

jobs:
  - name: rdpgmc
    resource_pool: rdpg
    persistent_disk: 512_000
    properties:
      <<: (( merge ))
      pgbdr:
        debug: "false"
        hba_config: |+
        # Any custom pg_hba.conf lines go here...
        max_connections: "100"
        shared_buffers: "512MB"
        effective_cache_size: "1536MB"
        work_mem: "262kB"
        maintenance_work_mem: "128MB"
        checkpoint_segments: "32"
        checkpoint_completion_target: "0.7"
        wal_buffers: "16MB"
        default_statistics_target: "100"
      pgbouncer:
        debug: "false"
        listen_port: 6432
        admin_user: "rdpgpbadmin"
        admin_pass: "rdpgadmin"
      haproxy:
        admin_user: haproxyadmin
        admin_pass: pleasechangethis
        admin_port: 9999
      rdpgd_manager:
        debug: "false"
        log_level: "info"
        cluster_name: "rdpgmc"
        db_pass: "pleasechangethis"

  - name: rdpgsc1
    resource_pool: rdpg
    persistent_disk_pool: rdpgsc_disk
    properties:
      pgbdr:
        debug: "false"
        hba_config: |+
        # Any custom pg_hba.conf lines go here...
        max_connections: "100"
        shared_buffers: "512MB"
        effective_cache_size: "1536MB"
        work_mem: "262kB"
        maintenance_work_mem: "128MB"
        checkpoint_segments: "32"
        checkpoint_completion_target: "0.7"
        wal_buffers: "16MB"
        default_statistics_target: "100"
      pgbouncer:
        debug: "false"
        listen_port: 6432
        admin_user: "rdpgpbadmin"
        admin_pass: "rdpgadmin"
      haproxy:
        admin_user: haproxyadmin
        admin_pass: pleasechangethis
        admin_port: 9999
      rdpgd_service:
        debug: "false"
        log_level: "info"
        cluster_name: "rdpgsc1"
        pool_size: 20
        db_pass: "pleasechangethis"

  - name: rdpgsc2
    resource_pool: rdpg
    persistent_disk_pool: rdpgsc_disk
    properties:
      pgbdr:
        debug: "false"
        hba_config: |+
        # Any custom pg_hba.conf lines go here...
        max_connections: "100"
        shared_buffers: "512MB"
        effective_cache_size: "1536MB"
        work_mem: "262kB"
        maintenance_work_mem: "128MB"
        checkpoint_segments: "32"
        checkpoint_completion_target: "0.7"
        wal_buffers: "16MB"
        default_statistics_target: "100"
      pgbouncer:
        debug: "false"
        listen_port: 6432
        admin_user: "rdpgpbadmin"
        admin_pass: "rdpgadmin"
      haproxy:
        admin_user: haproxyadmin
        admin_pass: pleasechangethis
        admin_port: 9999
      rdpgd_service:
        debug: "false"
        log_level: "info"
        cluster_name: "rdpgsc2"
        pool_size: 20
        db_pass: "pleasechangethis"

  - name: acceptance_tests
    networks:
      - name: rdpg
        default: [dns, gateway]

compilation:
  cloud_properties:
    instance_type: m3.medium

resource_pools:
  - name: rdpg
    cloud_properties:
      instance_type: m3.medium

  - name: errand_a
    cloud_properties:
      instance_type: m3.medium

networks: (( merge ))

properties: {}
