---
meta:
  environment: rdpg-warden

  stemcell:
    name: bosh-warden-boshlite-centos-7-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: rdpg
    instances: 5
    templates:
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: consul
      release: rdpg
    networks:
      - name: rdpg
        static_ips:
          - 10.244.2.2
          - 10.244.2.6
          - 10.244.2.10
          - 10.244.2.14
          - 10.244.2.18
    properties:
      pgbdr:
        debug: "true"
        hba: |
          host    replication   postgres 10.0.2.15/32  trust
          host    all           postgres 10.0.2.15/32  trust
        nodes:
          - 10.244.2.2
          - 10.244.2.6
          - 10.244.2.10
          - 10.244.2.14
          - 10.244.2.18
        max_connections: "100"
        shared_buffers: "128MB"
        effective_cache_size: "256MB"
        work_mem: "2MB"
        maintenance_work_mem: "16MB"
        checkpoint_segments: "16"
        checkpoint_completion_target: "0.7"
        wal_buffers: "1MB"
        default_statistics_target: "100"
      pgbouncer:
        debug: "true"
        admin_pass: "rdpgadmin"
      consul: {}

properties: {}

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: rdpg
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static:
    - 10.244.2.6
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static:
    - 10.244.2.10
  - cloud_properties:
      name: random
    range: 10.244.2.12/30
    reserved:
    - 10.244.2.13
    static:
    - 10.244.2.14
  - cloud_properties:
      name: random
    range: 10.244.2.16/30
    reserved:
    - 10.244.2.17
    static:
    - 10.244.2.18

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.2.20/30
    reserved:
    - 10.244.2.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.24/30
    reserved:
    - 10.244.2.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.28/30
    reserved:
    - 10.244.2.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.32/30
    reserved:
    - 10.244.2.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.36/30
    reserved:
    - 10.244.2.37
    static: []
