meta:
  environment: (( merge ))
  stemcell: (( merge ))

name: (( meta.environment ))

director_uuid: (( merge ))

releases: (( merge ))

networks: (( merge ))

jobs: (( merge ))

properties: (( merge ))

compilation:
  workers: 1
  network: rdpg
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 6
  max_in_flight: 6
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  serial: false

resource_pools:
  - name: rdpg
    network: rdpg
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: errand_a
    network: rdpg
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))
