meta:
  environment: (( merge ))
  stemcell: (( merge ))

name: (( meta.environment ))

director_uuid: (( merge ))

releases: (( merge ))

networks: (( merge ))

jobs: (( merge ))

properties: (( merge ))

compilation:
  workers: 2
  network: rdpg
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 4
  canary_watch_time: 1000-360000
  update_watch_time: 1000-360000
  serial: false

resource_pools:
  - name: pool_z1
    network: rdpg
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: errand_z1
    network: rdpg
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))
