meta:
  environment: ~

disk_pools:
- name: rdpgsc_disk
  disk_size: (( merge ))
  cloud_properties: (( merge ))

networks: ((merge))

properties: ((merge))

jobs:
  - name: rdpgmc
    persistent_disk: (( merge ))
    networks:
    - name: rdpg
      static_ips: (( static_ips(0,1,2) ))
    properties:
     <<: (( merge ))
     consul:
       debug: "false"
       server: true
       join_node: (( jobs.rdpgmc.networks.rdpg.static_ips.[0] ))
       join_nodes: (( jobs.rdpgmc.networks.rdpg.static_ips ))
    resource_pool: rdpg
    instances: 3
    update:
      serial: true
      canaries: 0
      max_in_flight: 1
    templates:
    - name: consul
      release: rdpg
    - name: pgbdr
      release: rdpg
    - name: rdpgd-manager
      release: rdpg
    - name: pgbouncer
      release: rdpg


  - name: rdpgsc1
    persistent_disk_pool: (( merge ))
    networks:
    - name: rdpg
      static_ips: (( static_ips(3,4) ))
    properties:
      <<: (( merge ))
      consul:
        debug: "false"
        server: false
        join_node: (( jobs.rdpgmc.networks.rdpg.static_ips.[0] ))
    resource_pool: rdpg
    instances: 2
    update:
      canaries: 0
      max_in_flight: 2
    templates:
    - name: consul
      release: rdpg
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: haproxy
      release: rdpg
    - name: rdpgd-service
      release: rdpg

  - name: rdpgsc2
    persistent_disk_pool: (( merge ))
    networks:
    - name: rdpg
      static_ips: (( static_ips(5,6) ))
    properties:
      <<: (( merge ))
      consul:
        debug: "false"
        server: false
        join_node: (( jobs.rdpgmc.networks.rdpg.static_ips.[0] ))
    resource_pool: rdpg
    instances: 2
    update:
      canaries: 0
      max_in_flight: 2
    templates:
    - name: consul
      release: rdpg
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: haproxy
      release: rdpg
    - name: rdpgd-service
      release: rdpg

  - name: acceptance_tests
    resource_pool: errand_a
    networks: (( merge ))
    templates:
    - name: acceptance-tests
      release: rdpg
    instances: 1
    lifecycle: errand
