meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: pgbdr
    templates:
    - name: pgbdr
      release: pgbdr
    - name: pgbouncer
      release: pgbdr
    - name: consul
      release: pgbdr
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties: ((merge))

networks: (( merge ))

properties: ((merge))
