meta:
  environment: ~

networks: ((merge))

properties: ((merge))

jobs:
  - name: rdpg_manager
    instances: 3

    resource_pool: manager_cluster
    networks: (( merge ))
    persistent_disk: 65536
    update:
      canaries: 3

    templates:
    - name: consul
      release: rdpg
    - name: consul-template
      release: rdpg
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: haproxy
      release: rdpg
    - name: rdpgd-manager
      release: rdpg

    properties: ((merge))

  - name: rdpg_cluster_1

    instances: 2

    resource_pool: service_cluster_a
    networks: (( merge ))
    persistent_disk: 65536
    update:
      canaries: 2

    templates:
    - name: consul
      release: rdpg
    - name: consul-template
      release: rdpg
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: haproxy
      release: rdpg
    - name: rdpgd-service
      release: rdpg

    properties: ((merge))

  - name: acceptance_tests
    templates:
    - name: acceptance-tests
    instances: 1
    lifecycle: errand
    resource_pool: errand_a
    networks: (( merge ))

