meta:
  environment: ~

networks: ((merge))

properties: ((merge))

jobs:
  - name: rdpg

    instances: 5

    resource_pool: cluster_a
    networks: (( merge ))
    persistent_disk: 65536
    update:
      canaries: 10

    templates:
    - name: consul
      release: rdpg
    - name: consul-template
      release: rdpg
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: haproxy
      release: rdpg
    - name: rdpg-agent
      release: rdpg

    properties: ((merge))

  - name: acceptance_tests
    templates:
    - name: acceptance-tests
      release: rdpg
    instances: 1
    lifecycle: errand
    resource_pool: errand_a
    networks: (( merge ))
