meta:
  environment: ~

networks: ((merge))

properties: ((merge))

jobs:
  - name: rdpgmc
    networks: (( merge ))
    properties: (( merge ))
    resource_pool: rdpg
    instances: 3
    update:
      canaries: 3
    templates:
    - name: consul
      release: rdpg
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: rdpgd-manager
      release: rdpg
    - name: remote_syslog
      release: rdpg

  - name: rdpgsc1
    networks: (( merge ))
    properties: (( merge ))
    resource_pool: rdpg
    instances: 2
    update:
      canaries: 2
    templates:
    - name: consul
      release: rdpg
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: haproxy
      release: rdpg
    - name: rdpgd-service
      release: rdpg
    - name: remote_syslog
      release: rdpg

  - name: rdpgsc2
    networks: (( merge ))
    properties: (( merge ))
    resource_pool: rdpg
    instances: 2
    update:
      canaries: 2
    templates:
    - name: consul
      release: rdpg
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: haproxy
      release: rdpg
    - name: rdpgd-service
      release: rdpg
    - name: remote_syslog
      release: rdpg

  - name: acceptance_tests
    resource_pool: errand_a
    networks: (( merge ))
    templates:
    - name: acceptance-tests
      release: rdpg
    instances: 1
    lifecycle: errand
