meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: rdpg
    templates:
    - name: pgbdr
      release: rdpg
    - name: pgbouncer
      release: rdpg
    - name: consul
      release: rdpg
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 65536
    update:
      canaries: 10
    properties: ((merge))

networks: ((merge))

properties: ((merge))
