jobs:
- name: deploy
  public: true
  serial: true
  plan:
  - get: boshrelease
    resource: git-rdpg-boshrelease
    trigger: true
  - task: create-release-and-deploy
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: boshrelease, path: rdpg-boshrelease}
      run:
        path: ./rdpg-boshrelease/ci/scripts/create_release_and_deploy.sh
        args: []
      params:
        bosh_target: {{bosh-lite-build-target}}
        bosh_username: {{bosh-lite-build-username}}
        bosh_password: {{bosh-lite-build-password}}
        bosh_deployment_name: {{bosh-lite-build-deployment-name}}
  - task: bosh-run-errand-acceptance-tests
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
        - {name: create-release-and-deploy, path: .}
      run:
        path: ./rdpg-boshrelease/ci/scripts/acceptance_tests.sh
        args: []
      params:
        bosh_target: {{bosh-lite-build-target}}
        bosh_username: {{bosh-lite-build-username}}
        bosh_password: {{bosh-lite-build-password}}

resources:
- name: git-rdpg-boshrelease
  type: git
  source:
    uri: {{pipeline-git-repo}}
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
