jobs:
- name: bump-tests
  public: true
  serial: true
  plan:
  - aggregate:
    - get: rdpg-boshrelease
      resource: git-rdpg-boshrelease
    - get: rdpg-acceptance-tests
      resource: git-rdpg-acceptance-tests
      trigger: true
  - task: update-subtree
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: rdpg-boshrelease}
      - {name: rdpg-acceptance-tests}
      run:
        path: ./rdpg-boshrelease/ci/scripts/update_acceptance_tests.sh
        args: [rdpg-acceptance-tests]
  - put: git-rdpg-boshrelease
    params:
      repository: update-subtree/rdpg-boshrelease
      rebase: true

- name: bump-rdpgd
  public: true
  serial: true
  plan:
  - aggregate:
    - get: rdpg-boshrelease
      resource: git-rdpg-boshrelease
    - get: rdpgd
      resource: git-rdpgd
      trigger: true
  - task: update-subtree
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: rdpg-boshrelease}
      - {name: rdpgd}
      run:
        path: ./rdpg-boshrelease/ci/scripts/update_acceptance_tests.sh
        args: [rdpgd]
  - put: git-rdpg-boshrelease
    params:
      repository: update-subtree/rdpg-boshrelease
      rebase: true

- name: deploy
  public: true
  serial: true
  plan:
  - aggregate:
    - get: rdpg-boshrelease
      resource: git-rdpg-boshrelease
    - get: git-rdpg-boshrelease-release-changes
      trigger: true
  - task: create-release-and-deploy
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: rdpg-boshrelease}
      run:
        path: ./rdpg-boshrelease/ci/scripts/create_release_and_deploy.sh
        args: []
      params:
        bosh_target: {{bosh-lite-build-target}}
        bosh_username: {{bosh-lite-build-username}}
        bosh_password: {{bosh-lite-build-password}}
        bosh_deployment_name: {{bosh-lite-build-deployment-name}}
  - task: bosh-run-errand-acceptance-tests
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
        - {name: create-release-and-deploy, path: .}
      run:
        path: ./rdpg-boshrelease/ci/scripts/acceptance_tests.sh
        args: []
      params:
        bosh_target: {{bosh-lite-build-target}}
        bosh_username: {{bosh-lite-build-username}}
        bosh_password: {{bosh-lite-build-password}}

- name: rc
  public: true
  plan:
  - aggregate:
    - get: boshrelease
      resource: git-rdpg-boshrelease
      passed: [deploy]
      trigger: true
    - get: version
      trigger: false
      params: {bump: patch, pre: rc}
  - put: version
    params: {file: version/number}

- name: shipit
  public: true
  serial: true
  plan:
  - aggregate:
    - get: version
      passed: [rc]
      params: {bump: final}
    - get: boshrelease
      resource: git-rdpg-boshrelease
      passed: [rc]
  - task: create-final-release
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: boshrelease, path: rdpg-boshrelease}
      - {name: version}
      run:
        path: ./rdpg-boshrelease/ci/scripts/shipit.sh
        args: []
      params:
        release_name: "Reliable Distributed PostgreSQL"
        bosh_target: {{bosh-lite-build-target}}
        bosh_username: {{bosh-lite-build-username}}
        bosh_password: {{bosh-lite-build-password}}
        bosh_deployment_name: {{bosh-lite-build-deployment-name}}
        aws_access_key_id: {{boshrelease-aws-access-key-id}}
        aws_secret_access_key: {{boshrelease-aws-secret-access-key}}
        promotion_branch: master
  - put: git-rdpg-boshrelease
    params:
      repository: create-final-release/rdpg-boshrelease
      rebase: true
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: final-release
      params: {from: create-final-release/rdpg-boshrelease/releases/rdpg/rdpg-(.*).tgz}
    - put: github-final-release
      params:
        name: create-final-release/rdpg-boshrelease/release/name
        tag: create-final-release/rdpg-boshrelease/release/tag
        body: create-final-release/rdpg-boshrelease/release/notes.md
        globs: [create-final-release/rdpg-boshrelease/releases/rdpg/rdpg-*.tgz]

resources:
- name: version
  type: semver
  source:
    key: current-version
    bucket: {{pipeline-aws-bucket}}
    access_key_id: {{pipeline-aws-access-key-id}}
    secret_access_key: {{pipeline-aws-secret-access-key}}
    initial_version: 0.2.0

- name: git-rdpg-boshrelease
  type: git
  source:
    uri: git@github.com:starkandwayne/rdpg-boshrelease.git
    branch: master
    private_key: {{github-private-key}}

- name: git-rdpg-boshrelease-release-changes
  type: git
  source:
    uri: git@github.com:starkandwayne/rdpg-boshrelease.git
    branch: master
    private_key: {{github-private-key}}
    paths:
      - src/**/*
      - jobs/**/*
      - packages/**/*
      - config/blobs.yml

- name: git-rdpgd
  type: git
  source:
    uri: https://github.com/starkandwayne/rdpgd.git
    branch: master

- name: git-rdpg-acceptance-tests
  type: git
  source:
    uri: https://github.com/starkandwayne/rdpg-acceptance-tests.git
    branch: master

- name: github-final-release
  type: github-release
  source:
    user: starkandwayne
    repository: rdpg-boshrelease
    access_token: {{github-access-token}}

- name: final-release
  type: s3
  source:
    bucket: {{boshrelease-aws-bucket}}
    regexp: rdpg-(.*).tgz
    access_key_id: {{boshrelease-aws-access-key-id}}
    secret_access_key: {{boshrelease-aws-secret-access-key}}
