jobs:
- name: deploy
  public: true
  serial: true
  plan:
  - get: boshrelease
    resource: git-rdpg-boshrelease
    trigger: true
  - task: delete-existing
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: boshrelease, path: .}
      run:
        path: ./ci/scripts/delete_existing_deployment.sh
        args: []
      params:
        bosh_target: {{bosh-lite-build-target}}
        bosh_username: {{bosh-lite-build-username}}
        bosh_password: {{bosh-lite-build-password}}
        bosh_deployment_name: {{bosh-lite-build-deployment-name}}

resources:
- name: git-rdpg-boshrelease
  type: git
  source:
    uri: {{pipeline-git-repo}}
    branch: {{pipeline-branch}}
    private_key: {{github-private-key}}
